// vue/src/components/Footer.vue
<script setup lang="ts">
// Footer component - no complex logic needed
</script>

<template>
  <footer class="bg-black bg-opacity-20 py-8">
    <div class="max-w-6xl mx-auto px-6 text-center">
      <p class="text-white">
        &copy; 2024 Awesome GSAP Examples. Built with ❤️ and GSAP + Vue 3.
      </p>
    </div>
  </footer>
</template>

<style scoped>
/* Component-specific styles */
</style>

// react/src/components/Footer.tsx
'use client'

const Footer = () => {
  return (
    <footer className="bg-black bg-opacity-20 py-8">
      <div className="max-w-6xl mx-auto px-6 text-center">
        <p className="text-white">
          &copy; 2024 Awesome GSAP Examples. Built with ❤️ and GSAP + React + Next.js.
        </p>
      </div>
    </footer>
  )
}

export default Footer
